/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AllocationMethod = "branch" | "capacity" | "escalation" | "partner" | "round_robin" | "specialist";

export type ApplicantScope = "applicant" | "business" | "co_applicant" | "guarantor";

export type AttributionStatus = "merged_into" | "original" | "reassigned";

export type AuditAction = "abac_deny" | "allocate" | "attribution_change" | "break_glass_access" | "comm_send" | "config_change" | "consent_expire" | "consent_grant" | "consent_withdraw" | "doc_delete" | "doc_download" | "doc_upload" | "doc_verify" | "doc_view" | "doc_waive" | "eligibility_request" | "export_download" | "export_generate" | "handoff_attempt" | "handoff_failure" | "handoff_success" | "kyc_exception" | "kyc_request" | "kyc_response" | "lead_create" | "lead_merge" | "lead_override" | "lead_update" | "link_create" | "link_open" | "link_revoke" | "login" | "login_failed" | "logout" | "mfa_failed" | "nurture" | "reassign" | "rejection" | "reopen" | "role_change" | "stage_transition" | "user_change" | "view_sensitive";

export type Capability = "allocate" | "audit_trail" | "break_glass" | "bulk_action" | "configuration" | "consent_ledger" | "create_lead" | "customer_comm" | "edit_lead" | "export" | "hand_off" | "kyc_signoff" | "move_stage" | "reports" | "upload_doc" | "user_mgmt" | "verify_doc" | "view_lead";

export type CommCategory = "marketing" | "transactional";

export type CommChannel = "email" | "in_app" | "sms" | "whatsapp";

export type ConfigChangeStatus = "active" | "approved" | "pending" | "rejected" | "rolled_back";

export type ConfigStatus = "active" | "draft" | "retired";

export type ConsentActor = "customer" | "partner" | "rm" | "system";

export type ConsentPurpose = "aa_bank_data" | "communication" | "document_processing" | "grievance" | "gst_business_data" | "kyc" | "lead_contact" | "los_handoff" | "marketing" | "partner_sharing" | "product_eligibility";

export type ConsentState = "denied" | "expired" | "granted" | "superseded" | "withdrawn";

export type ConsentStatus = "captured" | "partial" | "pending" | "withdrawn";

export type CreationChannel = "api" | "bulk" | "manual" | "missed_call" | "partner" | "qr" | "telecalling" | "website";

export type CustomerType = "business" | "individual";

export type DataCategory = "asset" | "behavioural" | "consent" | "contact" | "financial" | "identity" | "kyc_doc";

export type DataClassification = "confidential" | "internal" | "pii" | "public" | "restricted" | "sensitive";

export type DataScope = "A" | "B" | "C" | "M" | "O" | "P" | "R" | "T" | "X";

export type DeliveryStatus = "delivered" | "failed" | "queued" | "sent";

export type Disposition = "callback_requested" | "connected" | "docs_promised" | "no_answer" | "not_interested" | "rescheduled" | "visited" | "wrong_number";

export type DlaType = "dla" | "lsp" | "partner";

export type DocStatus = "expired" | "mismatch" | "not_required" | "pending" | "under_review" | "uploaded" | "verified" | "waived";

export type DocType = "address" | "bank" | "gst" | "id" | "income" | "insurance" | "itr" | "land_record" | "other" | "pan" | "permit" | "photo" | "property" | "quotation" | "rc" | "title" | "valuation" | "work_order";

export type DupAction = "blocked" | "linked" | "merged" | "overridden" | "queued" | "warned";

export type DupRecordStatus = "open" | "resolved";

export type DupStatus = "flagged" | "linked" | "merged" | "none";

export type EligibilityStatus = "failed" | "pending" | "received";

export type EventCode = "CONFIG_CHANGED" | "CONSENT_PENDING" | "CONSENT_WITHDRAWN" | "DATA_RIGHT_REQUEST" | "DOC_MISMATCH" | "DOC_REQUEST" | "DOC_UPLOADED" | "DUPLICATE_FLAGGED" | "ELIGIBILITY_RECEIVED" | "EXPORT_COMPLETED" | "FIRST_CONTACT_BREACH" | "FIRST_CONTACT_DUE" | "GRIEVANCE_CREATED" | "HANDOFF_FAILED" | "HANDOFF_READY" | "HOT_LEAD" | "KYC_EXCEPTION" | "LEAD_ASSIGNED" | "LEAD_CREATED" | "LEAD_HANDED_OFF" | "LEAD_STAGE_CHANGED";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type GrantStatus = "active" | "expired" | "pending" | "revoked";

export type GrievanceCategory = "data_privacy" | "document_issue" | "mis_selling" | "other" | "service_delay" | "staff_conduct";

export type GrievanceSource = "admin" | "branch" | "call_centre" | "customer_link" | "partner" | "rm";

export type GrievanceStatus = "closed" | "escalated" | "in_progress" | "open" | "resolved";

export type IntegrationDirection = "inbound" | "outbound";

export type IntegrationKind = "aa" | "aadhaar" | "asset" | "bureau_via_los" | "campaign" | "ckyc" | "comm" | "cti" | "digilocker" | "gst" | "los_eligibility" | "los_handoff" | "los_status" | "pan" | "vcip";

export type IntegrationStatus = "failed" | "pending" | "retrying" | "success";

export type JobStatus = "awaiting_approval" | "completed" | "failed" | "queued" | "running";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type KycCheckStatus = "exception" | "failed" | "initiated" | "success" | "waived";

export type KycException = "address_mismatch" | "ckyc_unavailable" | "duplicate_ckyc" | "expired" | "name_mismatch" | "pan_mismatch" | "provider_down" | "unreadable" | "vcip_failed";

export type KycStatus = "exception" | "in_progress" | "not_started" | "verified" | "waived";

export type KycType = "aadhaar_otp" | "ckyc" | "digilocker" | "manual" | "pan" | "vcip";

export type Lang = "Bengali" | "English" | "Gujarati" | "Hindi" | "Kannada" | "Marathi" | "Tamil" | "Telugu";

export type LeadOutcome = "any" | "dormant" | "handed_off" | "rejected";

export type LeadSource = "Branch" | "Dealer" | "DSA" | "Field" | "Referral" | "Telecalling" | "Website";

export type LeadStage = "assigned" | "captured" | "consent_pending" | "contacted" | "documents_pending" | "dormant" | "eligibility_requested" | "first_contact_pending" | "handed_off" | "kyc_in_progress" | "qualified" | "ready_for_handoff" | "rejected";

export type LinkStatus = "active" | "expired" | "revoked" | "used";

export type MaskingLevel = "full" | "partial" | "unmasked";

export type MatchConfidence = "medium" | "strong" | "weak";

export type MirrorSource = "poll" | "webhook";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OutboxStatus = "failed" | "pending" | "published";

export type PanTiming = "at_capture" | "before_handoff" | "before_kyc";

export type PartnerStatus = "active" | "expired" | "suspended";

export type PartnerType = "Aggregator" | "Connector" | "Dealer" | "DSA" | "OEM" | "Referral";

export type Priority = "high" | "low" | "normal";

export type ProductCode = "CAR" | "CE" | "CV" | "HRM" | "SBL" | "TRACTOR" | "TW";

export type RejectionPrimary = "asset_unacceptable" | "consent_withdrawn" | "document_incomplete" | "duplicate" | "kyc_mismatch" | "low_income" | "no_response" | "not_interested" | "other" | "out_of_area" | "partner_withdrawal" | "product_unsuitable";

export type RetentionAction = "anonymise" | "purge";

export type RightsStatus = "fulfilled" | "in_review" | "open" | "rejected_retained";

export type RightsType = "access" | "correction" | "erasure" | "grievance" | "update" | "withdrawal";

export type RiskBand = "high" | "low" | "medium";

export type RoleCode = "ADMIN" | "BM" | "CUSTOMER" | "DPO" | "HEAD" | "KYC" | "PARTNER" | "RM" | "SM";

export type ScanStatus = "clean" | "infected" | "pending";

export type ShareStatus = "failed" | "shared";

export type SlaTarget = "document" | "first_contact" | "grievance" | "handoff_retry" | "kyc_exception";

export type SubjectType = "customer" | "user";

export type TaskStatus = "cancelled" | "done" | "in_progress" | "open" | "overdue";

export type TaskType = "approval" | "call" | "callback" | "dealer_followup" | "doc_request" | "handoff_retry" | "kyc_appt" | "nurture" | "visit";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UploadChannel = "customer_link" | "digilocker" | "partner" | "rm";

export type UserStatus = "active" | "inactive" | "locked";

export type ValidationStatus = "incomplete" | "invalid" | "valid";

export interface AllocationRules {
  allocation_rule_id: Generated<string>;
  capacity_limit: number | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  criteria: Json;
  is_active: Generated<boolean>;
  method: AllocationMethod;
  name: string;
  org_id: Generated<string>;
  priority_order: number;
  target: Json;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface AuditLogs {
  action: AuditAction;
  actor_id: string;
  after_hash: string | null;
  audit_id: Generated<string>;
  before_hash: string | null;
  created_at: Generated<Timestamp>;
  detail: Json | null;
  entity_id: string | null;
  entity_type: string;
  ip_device: Json | null;
  lead_id: string | null;
  org_id: Generated<string>;
  prev_audit_hash: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Branches {
  address: string | null;
  branch_id: Generated<string>;
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  is_active: Generated<boolean>;
  name: string;
  org_id: Generated<string>;
  pin_codes: Json | null;
  region_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface BreakGlassGrants {
  approver_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  grant_id: Generated<string>;
  grantee_id: string;
  org_id: Generated<string>;
  reason: string;
  scope_ref: string | null;
  scope_type: string;
  status: Generated<GrantStatus>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  valid_from: Timestamp;
  valid_until: Timestamp;
}

export interface BusinessCalendars {
  branch_id: string | null;
  business_calendar_id: Generated<string>;
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  holidays: Json | null;
  is_active: Generated<boolean>;
  is_default: Generated<boolean>;
  name: string;
  org_id: Generated<string>;
  region_id: string | null;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  working_hours: Json;
}

export interface CommunicationLogs {
  channel: CommChannel;
  communication_log_id: Generated<string>;
  consent_basis: ConsentPurpose | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  failure_reason: string | null;
  lead_id: string | null;
  org_id: Generated<string>;
  provider_ref: string | null;
  recipient: string;
  sent_at: Timestamp | null;
  status: Generated<DeliveryStatus>;
  template_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface CommunicationTemplates {
  body: string;
  category: CommCategory;
  channel: CommChannel;
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  language: Lang;
  org_id: Generated<string>;
  product_code: ProductCode | null;
  status: Generated<ConfigStatus>;
  template_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  version: number;
}

export interface ConfigurationVersions {
  checker_id: string | null;
  config_ref: string | null;
  config_type: string;
  configuration_version_id: Generated<string>;
  created_at: Generated<Timestamp>;
  created_by: string;
  diff: Json | null;
  effective_at: Timestamp | null;
  maker_id: string;
  org_id: Generated<string>;
  rollback_ref: string | null;
  status: Generated<ConfigChangeStatus>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  version: number;
}

export interface ConsentRecords {
  actor: ConsentActor;
  channel: CreationChannel;
  consent_id: Generated<string>;
  consent_text_version: string;
  created_at: Generated<Timestamp>;
  customer_profile_id: string | null;
  data_category: DataCategory | null;
  expires_at: Timestamp | null;
  ip_device: Json | null;
  language: Lang | null;
  lead_id: string;
  notice_version: string;
  org_id: Generated<string>;
  purpose: ConsentPurpose;
  state: ConsentState;
  superseded_by: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CustomerLinks {
  created_at: Generated<Timestamp>;
  created_by: string;
  customer_link_id: Generated<string>;
  expires_at: Generated<Timestamp>;
  lead_id: string;
  opened_at: Timestamp | null;
  org_id: Generated<string>;
  otp_verified_at: Timestamp | null;
  purpose: Json;
  revoked_by: string | null;
  status: Generated<LinkStatus>;
  token_hash: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface CustomerProfiles {
  address: Json | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  customer_profile_id: Generated<string>;
  customer_type: CustomerType;
  deleted_at: Timestamp | null;
  display_name: string;
  is_existing_customer: Generated<boolean>;
  org_id: Generated<string>;
  preferred_language: Lang | null;
  primary_mobile: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface DataRightsRequests {
  created_at: Generated<Timestamp>;
  created_by: string;
  customer_profile_id: string;
  data_rights_request_id: Generated<string>;
  disposition: string | null;
  due_at: Timestamp | null;
  lead_id: string | null;
  org_id: Generated<string>;
  owner_id: string | null;
  request_type: RightsType;
  status: Generated<RightsStatus>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface DataSharingLogs {
  consent_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  data_category: DataCategory;
  data_sharing_log_id: Generated<string>;
  lead_id: string;
  org_id: Generated<string>;
  purpose: ConsentPurpose;
  recipient: string;
  shared_at: Generated<Timestamp>;
  status: Generated<ShareStatus>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface DlaRegistry {
  created_at: Generated<Timestamp>;
  created_by: string;
  data_collected: Json | null;
  dla_registry_id: Generated<string>;
  enabled_products: Json | null;
  grievance_officer: Json | null;
  name: string;
  org_id: Generated<string>;
  owner: string | null;
  status: Generated<ConfigStatus>;
  storage_location: string | null;
  type: DlaType;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  url: string | null;
}

export interface Documents {
  applicant_scope: ApplicantScope;
  classification: Generated<DataClassification>;
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  doc_type: DocType;
  document_id: Generated<string>;
  expires_at: Timestamp | null;
  file_size_kb: number | null;
  file_type: string | null;
  lead_id: string;
  org_id: Generated<string>;
  status: Generated<DocStatus>;
  storage_ref: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  uploaded_via: UploadChannel | null;
  verified_by: string | null;
  version: Generated<number>;
  virus_scan_status: Generated<ScanStatus>;
  waiver_reason: string | null;
}

export interface DuplicateMatches {
  action: Generated<DupAction>;
  action_by: string | null;
  action_reason: string | null;
  confidence: MatchConfidence;
  created_at: Generated<Timestamp>;
  created_by: string;
  duplicate_match_id: Generated<string>;
  lead_id: string;
  matched_lead_id: string;
  matched_on: Json;
  org_id: Generated<string>;
  status: Generated<DupRecordStatus>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface EligibilitySnapshots {
  conditions: Json | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  eligibility_snapshot_id: Generated<string>;
  indicative_amount: Numeric | null;
  lead_id: string;
  org_id: Generated<string>;
  rate_range: string | null;
  request_ref: string;
  response_basis: string | null;
  status: Generated<EligibilityStatus>;
  tenure_months: number | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  validity_until: Timestamp | null;
}

export interface EventOutbox {
  aggregate_id: string;
  aggregate_type: string;
  created_at: Generated<Timestamp>;
  event_code: EventCode;
  event_id: Generated<string>;
  org_id: Generated<string>;
  payload: Json;
  published_at: Timestamp | null;
  schema_version: Generated<number>;
  status: Generated<OutboxStatus>;
  updated_at: Generated<Timestamp>;
}

export interface ExportJobs {
  approver_id: string | null;
  artefact_ref: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  export_job_id: Generated<string>;
  filters: Json;
  masking_level: MaskingLevel;
  org_id: Generated<string>;
  report_code: string;
  requested_by: string;
  row_count: number | null;
  scope: DataScope;
  status: Generated<JobStatus>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface Grievances {
  category: GrievanceCategory;
  closure_proof_ref: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string;
  grievance_id: Generated<string>;
  grievance_no: string;
  lead_id: string | null;
  org_id: Generated<string>;
  owner_id: string | null;
  response: string | null;
  sla_due_at: Timestamp | null;
  source: GrievanceSource;
  status: Generated<GrievanceStatus>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface ImportJobs {
  created_at: Generated<Timestamp>;
  created_by: string;
  error_file_ref: string | null;
  failed_rows: number | null;
  file_ref: string;
  import_job_id: Generated<string>;
  org_id: Generated<string>;
  status: Generated<JobStatus>;
  success_rows: number | null;
  total_rows: number | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface IntegrationLogs {
  completed_at: Timestamp | null;
  correlation_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  direction: IntegrationDirection;
  error_code: string | null;
  http_status: number | null;
  idempotency_key: string | null;
  integration: IntegrationKind;
  integration_log_id: Generated<string>;
  lead_id: string | null;
  org_id: Generated<string>;
  request_ref: string | null;
  retry_count: Generated<number>;
  status: Generated<IntegrationStatus>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface KycVerifications {
  created_at: Generated<Timestamp>;
  created_by: string;
  exception_owner_id: string | null;
  exception_sla_due_at: Timestamp | null;
  exception_type: KycException | null;
  integration_log_id: string | null;
  kyc_type: KycType;
  kyc_verification_id: Generated<string>;
  lead_id: string;
  masked_response: Json | null;
  org_id: Generated<string>;
  provider: string | null;
  reference: string | null;
  resolution_code: string | null;
  status: Generated<KycCheckStatus>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface LeadIdentities {
  aadhaar_ref_token: string | null;
  address: Json | null;
  ckyc_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  dob: Timestamp | null;
  email: string | null;
  gstin: string | null;
  lead_identity_id: Generated<string>;
  mobile: string;
  name: string;
  org_id: Generated<string>;
  pan_masked: string | null;
  pan_token: string | null;
  preferred_language: Lang | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface LeadProductDetails {
  attributes: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string;
  lead_id: string;
  lead_product_detail_id: Generated<string>;
  org_id: Generated<string>;
  product_config_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  validation_status: Generated<ValidationStatus>;
}

export interface Leads {
  branch_id: string | null;
  channel_created_by: CreationChannel;
  consent_status: Generated<ConsentStatus>;
  created_at: Generated<Timestamp>;
  created_by: string;
  customer_profile_id: string | null;
  deleted_at: Timestamp | null;
  duplicate_status: Generated<DupStatus>;
  import_job_id: string | null;
  is_hot: Generated<boolean>;
  kyc_status: Generated<KycStatus>;
  lead_code: string;
  lead_id: Generated<string>;
  lead_identity_id: string;
  los_application_id: string | null;
  master_lead_id: string | null;
  nurture_next_at: Timestamp | null;
  org_id: Generated<string>;
  owner_id: string | null;
  pin_code: string | null;
  priority: Generated<Priority>;
  product_code: ProductCode;
  product_config_id: string;
  rejection_reason_id: string | null;
  reopened_count: Generated<number>;
  requested_amount: Numeric | null;
  score: number | null;
  score_reasons: Json | null;
  sla_first_contact_due_at: Timestamp | null;
  source_attribution_id: string;
  stage: Generated<LeadStage>;
  team_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  version: Generated<number>;
}

export interface LosApplicationMirrors {
  correlation_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  lead_id: string;
  los_application_id: string;
  los_mirror_id: Generated<string>;
  org_id: Generated<string>;
  received_via: MirrorSource;
  status: string;
  status_date: Timestamp;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface Notes {
  author_id: string;
  body: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  is_internal: Generated<boolean>;
  lead_id: string;
  note_id: Generated<string>;
  org_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface NotificationPreferences {
  channel: CommChannel;
  created_at: Generated<Timestamp>;
  created_by: string;
  notification_preference_id: Generated<string>;
  opted_in: Generated<boolean>;
  org_id: Generated<string>;
  purpose: ConsentPurpose;
  subject_ref: string;
  subject_type: SubjectType;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface Notifications {
  body: string;
  created_at: Generated<Timestamp>;
  event_code: EventCode;
  is_read: Generated<boolean>;
  lead_id: string | null;
  notification_id: Generated<string>;
  org_id: Generated<string>;
  recipient_user_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Orgs {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Partners {
  agreement_ref: string | null;
  branch_id: string | null;
  commission_flag: Generated<boolean>;
  contact_mobile: string | null;
  contact_person: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  legal_name: string;
  mapped_rm_id: string | null;
  org_id: Generated<string>;
  partner_code: string;
  partner_id: Generated<string>;
  products: Json | null;
  quality_score: number | null;
  risk_category: RiskBand | null;
  status: Generated<PartnerStatus>;
  type: PartnerType;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  valid_until: Timestamp | null;
}

export interface ProductConfigs {
  created_at: Generated<Timestamp>;
  created_by: string;
  document_checklist: Json;
  eligibility_mapping: Json | null;
  field_schema: Json;
  name: string;
  org_id: Generated<string>;
  pan_required_at: Generated<PanTiming>;
  product_code: ProductCode;
  product_config_id: Generated<string>;
  sla_config: Json | null;
  status: Generated<ConfigStatus>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  version: number;
}

export interface Regions {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  name: string;
  org_id: Generated<string>;
  region_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface RejectionReasons {
  created_at: Generated<Timestamp>;
  created_by: string;
  is_active: Generated<boolean>;
  org_id: Generated<string>;
  primary_reason: RejectionPrimary;
  rejection_reason_id: Generated<string>;
  requires_remarks: Generated<boolean>;
  sub_reason: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface RetentionPolicies {
  action: RetentionAction;
  created_at: Generated<Timestamp>;
  created_by: string;
  data_category: DataCategory;
  is_active: Generated<boolean>;
  lead_outcome: LeadOutcome | null;
  legal_hold: Generated<boolean>;
  org_id: Generated<string>;
  retain_days: number;
  retention_policy_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface RolePermissions {
  capability: Capability;
  conditions: Json | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  max_scope: DataScope;
  org_id: Generated<string>;
  role_id: string;
  role_permission_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface Roles {
  code: RoleCode;
  created_at: Generated<Timestamp>;
  created_by: string;
  default_scope: DataScope;
  is_external: Generated<boolean>;
  name: string;
  org_id: Generated<string>;
  role_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface SavedViews {
  created_at: Generated<Timestamp>;
  created_by: string;
  filter_json: Json;
  is_shared: Generated<boolean>;
  name: string;
  org_id: Generated<string>;
  owner_id: string;
  saved_view_id: Generated<string>;
  scope: DataScope;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface Schemes {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  is_active: Generated<boolean>;
  name: string;
  org_id: Generated<string>;
  product_code: ProductCode | null;
  scheme_id: Generated<string>;
  subvention_flag: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  valid_from: Timestamp;
  valid_to: Timestamp;
}

export interface SlaPolicies {
  applies_to: SlaTarget;
  condition: Json | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  escalation_chain: Json;
  is_active: Generated<boolean>;
  name: string;
  org_id: Generated<string>;
  sla_policy_id: Generated<string>;
  threshold_minutes: number;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface SourceAttributions {
  attribution_status: Generated<AttributionStatus>;
  campaign_code: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  creator_channel: CreationChannel;
  org_id: Generated<string>;
  partner_id: string | null;
  source: LeadSource;
  source_attribution_id: Generated<string>;
  sub_source: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  utm: Json | null;
}

export interface StageHistory {
  actor_id: string;
  created_at: Generated<Timestamp>;
  from_stage: LeadStage | null;
  lead_id: string;
  occurred_at: Generated<Timestamp>;
  org_id: Generated<string>;
  reason: string | null;
  stage_history_id: Generated<string>;
  to_stage: LeadStage;
  updated_at: Generated<Timestamp>;
}

export interface Tasks {
  created_at: Generated<Timestamp>;
  created_by: string;
  disposition: Disposition | null;
  due_at: Timestamp;
  geo: Json | null;
  lead_id: string | null;
  next_action_at: Timestamp | null;
  org_id: Generated<string>;
  owner_id: string;
  priority: Generated<Priority>;
  result_note: string | null;
  sla_policy_id: string | null;
  status: Generated<TaskStatus>;
  task_id: Generated<string>;
  type: TaskType;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface Teams {
  branch_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  is_active: Generated<boolean>;
  manager_id: string | null;
  name: string;
  org_id: Generated<string>;
  team_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface Users {
  branch_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  email: string;
  full_name: string;
  last_login_at: Timestamp | null;
  mfa_enabled: Generated<boolean>;
  mobile: string | null;
  org_id: Generated<string>;
  partner_id: string | null;
  password_hash: string | null;
  product_skills: Json | null;
  region_id: string | null;
  reporting_manager_id: string | null;
  role_id: string;
  status: Generated<UserStatus>;
  team_id: string | null;
  totp_secret_enc: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  user_id: Generated<string>;
  username: string;
}

export interface WebhookSubscriptions {
  created_at: Generated<Timestamp>;
  created_by: string;
  event_code: EventCode;
  is_active: Generated<boolean>;
  last_status: DeliveryStatus | null;
  org_id: Generated<string>;
  secret_ref: string;
  target_url: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  webhook_subscription_id: Generated<string>;
}

export interface DB {
  allocation_rules: AllocationRules;
  audit_logs: AuditLogs;
  branches: Branches;
  break_glass_grants: BreakGlassGrants;
  business_calendars: BusinessCalendars;
  communication_logs: CommunicationLogs;
  communication_templates: CommunicationTemplates;
  configuration_versions: ConfigurationVersions;
  consent_records: ConsentRecords;
  customer_links: CustomerLinks;
  customer_profiles: CustomerProfiles;
  data_rights_requests: DataRightsRequests;
  data_sharing_logs: DataSharingLogs;
  dla_registry: DlaRegistry;
  documents: Documents;
  duplicate_matches: DuplicateMatches;
  eligibility_snapshots: EligibilitySnapshots;
  event_outbox: EventOutbox;
  export_jobs: ExportJobs;
  grievances: Grievances;
  import_jobs: ImportJobs;
  integration_logs: IntegrationLogs;
  kyc_verifications: KycVerifications;
  lead_identities: LeadIdentities;
  lead_product_details: LeadProductDetails;
  leads: Leads;
  los_application_mirrors: LosApplicationMirrors;
  notes: Notes;
  notification_preferences: NotificationPreferences;
  notifications: Notifications;
  orgs: Orgs;
  partners: Partners;
  product_configs: ProductConfigs;
  regions: Regions;
  rejection_reasons: RejectionReasons;
  retention_policies: RetentionPolicies;
  role_permissions: RolePermissions;
  roles: Roles;
  saved_views: SavedViews;
  schemes: Schemes;
  sla_policies: SlaPolicies;
  source_attributions: SourceAttributions;
  stage_history: StageHistory;
  tasks: Tasks;
  teams: Teams;
  users: Users;
  webhook_subscriptions: WebhookSubscriptions;
}
